/*
 *  Copyright (c) 2017, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 */
package com.comviva.hceservice.internalSdkListeners;

import android.util.Log;

import com.comviva.hceservice.common.CommonUtil;
import com.comviva.hceservice.common.SDKData;
import com.comviva.hceservice.common.Tags;
import com.comviva.hceservice.util.Constants;
import com.mastercard.mpsdk.interfaces.CardManagerEventListener;

/**
 * Utility class which helps the MPA to register multiple listeners for individual events
 * generated by the SDK.
 */
public class MdesCardManagerEventListener implements CardManagerEventListener {
    private SDKData sdkData = SDKData.getInstance();

    @Override
    public synchronized boolean onCardProvisionCompleted(String cardId) {

        CommonUtil.broadcastMessage(sdkData.getContext(), Constants.TOKEN_STATUS_UPDATED, cardId, Constants.TOKEN_ADD_SUCCESS );
        return true;
    }


    @Override
    public synchronized boolean onCardProvisionFailure(String errorCode, String errorMessage, Exception exception) {
        CommonUtil.broadcastMessage(sdkData.getContext(), Constants.TOKEN_STATUS_UPDATED, null, errorMessage);
        return true;
    }


    @Override
    public synchronized boolean onReplenishCompleted(String cardId, int numberOfTransactionCredentials) {

       // CommonUtil.broadcastMessage(sdkData.getContext(), Constants.TOKEN_STATUS_UPDATED, cardId, "onReplenishCompleted" );
        return true;
    }


    @Override
    public synchronized boolean onReplenishFailed(String tokenUniqueReference,
                                                  String errorCode,
                                                  String errorMessage,
                                                  Exception exception) {

      //  CommonUtil.broadcastMessage(sdkData.getContext(), Constants.TOKEN_STATUS_UPDATED, null, "onReplenishFailed" );

        return true;
    }


    @Override
    public synchronized boolean onDeleteCardCompleted(String cardId) {

        CommonUtil.broadcastMessage(sdkData.getContext(), Constants.TOKEN_STATUS_UPDATED, null, "onDeleteCardCompleted" );

        return true;
    }


    @Override
    public synchronized boolean onDeleteCardFailed(String cardId,
                                                   String errorCode,
                                                   String errorMessage,
                                                   Exception exception) {
        CommonUtil.broadcastMessage(sdkData.getContext(), Constants.TOKEN_STATUS_UPDATED, null, "onDeleteCardFailed" );


        return true;
    }


    @Override
    public synchronized boolean onCardPinChangeCompleted(String cardId) {
        Log.d(Tags.DEBUG_LOG.getTag(), "onCardPinChangeCompleted");

        return true;
    }


    @Override
    public synchronized boolean onCardPinChangeFailed(String cardId,
                                                      int mobilePinTriesRemaining,
                                                      String errorCode,
                                                      String errorMessage,
                                                      Exception exception) {
        Log.d(Tags.DEBUG_LOG.getTag(), "card added successfully");

        return true;
    }


    @Override
    public synchronized boolean onCardPinSetCompleted(String cardId) {
        Log.d(Tags.DEBUG_LOG.getTag(), "onCardPinSetCompleted");
        return true;
    }


    @Override
    public synchronized boolean onCardPinSetFailed(String cardId,
                                                   int mobilePinTriesRemaining,
                                                   String errorCode,
                                                   String errorMessage,
                                                   Exception exception) {
        Log.d(Tags.DEBUG_LOG.getTag(), "onCardPinSetFailed");

        return true;
    }


    @Override
    public synchronized boolean onWalletPinChangeCompleted() {
        Log.d(Tags.DEBUG_LOG.getTag(), "onWalletPinChangeCompleted");

        return true;
    }


    @Override
    public synchronized boolean onWalletPinChangeFailed(int mobilePinTriesRemaining,
                                                        String errorCode,
                                                        String errorMessage,
                                                        Exception exception) {
        Log.d(Tags.DEBUG_LOG.getTag(), "onWalletPinChangeFailed");

        return true;
    }


    @Override
    public synchronized boolean onSetWalletPinCompleted() {
        Log.d(Tags.DEBUG_LOG.getTag(), "onSetWalletPinCompleted");

        return true;
    }


    @Override
    public synchronized boolean onSetWalletPinFailed(int mobilePinTriesRemaining,
                                                     String errorCode,
                                                     String errorMessage,
                                                     Exception exception) {
        Log.d(Tags.DEBUG_LOG.getTag(), "onSetWalletPinFailed");

        return true;
    }


    @Override
    public synchronized boolean onSystemHealthCompleted() {
        Log.d(Tags.DEBUG_LOG.getTag(), "onSystemHealthCompleted");

        return true;
    }


    @Override
    public synchronized boolean onSystemHealthFailure(String errorCode, String errorMessage, Exception exception) {

        return true;
    }


    @Override
    public synchronized boolean onChangeCardMobilePinStarted(String cardId,
                                                             String taskId) {

        return true;
    }


    @Override
    public synchronized boolean onChangeWalletMobilePinStarted(String taskId) {

        return true;
    }


    @Override
    public synchronized boolean onCardMobilePinResetCompleted(String tokenUniqueReference) {

        return true;
    }


    @Override
    public synchronized boolean onWalletMobilePinResetCompleted() {

        return true;
    }


    @Override
    public synchronized boolean onTaskStatusCompleted(final String taskStatus) {

        return true;
    }


    @Override
    public synchronized boolean onTaskStatusFailed(String errorCode, String errorMessage, Exception exception) {

        return true;
    }


    @Override
    public synchronized boolean onRequestSessionCompleted() {

        return true;
    }


    @Override
    public synchronized boolean onRequestSessionFailed(String errorCode, String errorMessage, Exception exception) {

        return true;
    }
}
