OLD_LOCAL_PATH := $(LOCAL_PATH)
LOCAL_PATH      := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE    := cryptopp562
LOCAL_CFLAGS    :=
LOCAL_SRC_FILES := $(subst $(LOCAL_PATH)/./,,$(wildcard $(LOCAL_PATH)/./*.cpp))
LOCAL_EXPORT_CFLAGS := -DFOO=1
LOCAL_C_INCLUDES := $(LOCAL_PATH)/./src
include $(BUILD_STATIC_LIBRARY)

#Restore LOCAL_PATH
LOCAL_PATH := $(OLD_LOCAL_PATH)
