package com.comviva.hceservice.common;

/**
 * Created by amit.randhawa on 16-Aug-17.
 */
public enum Tags {
    CLIENT_APP_ID("clientAppId"),
    CLIENT_WALLET_ACCOUNT_ID("clientWalletAccountId"),
    EMAIL_ADDRESS("emailAddress"),
    PROTECTION_TYPE("protectionType"),
    IMEI("imei"),
    INACTIVE("INACTIVE"),
    FAILURE("FAILURE"),
    IMG_PDF("IMG_PDF"),
    CARD_SYMBOL("cardSymbol"),
    TERMS_CONDITION("termsAndConditions"),
    OS_NAME("os_name"),
    PROCESSING_FAILURE("Processing Failure"),
    HTTPS("https"),
    RGK("rgk"),
    MONTH("month"),
    YEAR("year"),
    DEVICE_FINGER_PRINT("deviceFingerprint"),
    PUBLIC_KEY_FINGER_PRINT("publicKeyFingerprint"),
    HTTP("http"),
    PAYMENT_APP_ID("paymentAppId"),
    ACCOUNT_NUMBER("accountNumber"),
    COUNT("count"),
    CVV_2("cvv2"),
    EXPIRY_MONTH("expiryMonth"),
    EXPIRATION_DATE("expirationDate"),
    NAME("name"),
    EXPIRY_YEAR("expiryYear"),
    SOURCE("source"),
    CARD_HOLDER_NAME("cardholderName"),
    SECURITY_CODE("securityCode"),
    ENCRYPTED_KEY("encryptedKey"),
    ENCRYPTED_DATA("encryptedData"),
    ELIGIBILITY_RECEIPT("eligibilityReceipt"),
    IV("iv"),
    AES_KEY("aesKey"),
    TOKEN_TYPE("tokenType"),
    T_N_C_ID("termsAndConditionsAssetId"),
    SERVICE_ID("serviceId"),
    CONSUMER_LANGUAGE("consumerLanguage"),
    CARD_INFO("cardInfo"),
    CARDLET_ID("cardletId"),
    PAYMENT_APP_INSTANCE_ID("paymentAppInstanceId"),
    DEVICE_UNDERSCORE_MODEL("device_model"),
    CAUSED_BY("causedBy"),
    DEVICE_MODEL("deviceModel"),
    PRESENTATION_TYPE("presentationType"),
    GCM_REG_ID("gcmRegistrationId"),
    CLIENT_DEVICE_ID("clientDeviceID"),
    CONSUER_ENTRY_MODE("consumerEntryMode"),
    DEVICE_INFO("deviceInfo"),
    VTS("vts"),
    MDES("mdes"),
    PAN_ENROLLMENT_ID("panEnrollmentID"),
    TERMS_AND_CONDITION_ID("termsAndConditionsID"),
    USER_ID("userId"),
    ACTIVATION_CODE("activationCode"),
    PUBLIC_KEY("publicKey"),
    INPUT_STREAM("inputStream"),
    USER_DETAILS("userDetails"),
    MDES_PAY_INSTANCE_ID("paymentAppInstanceID"),
    TOKEN_INFO("tokenInfo"),
    TOKENS("tokens"),
    MAC("mac"),
    API("api"),
    SC("sc"),
    SCHEME_TYPE("schemeType"),
    TV1("tvl"),
    TOKEN_UNIQUE_REFERENCES("tokenUniqueReferences"),
    TOKEN_UNIQUE_REFERENCE("tokenUniqueReference"),
    REGISTRATION_STATUS("registrationStatus"),
    AUTHENTICATION_CODE_ID("authenticationCodeId"),
    AUTHENTICATION_CODE("authenticationCode"),
    OTP_VALUE("otpValue"),V_PROVISIONED_TOKEN_ID("vProvisionedTokenID"),REQUEST_LOG("REQUEST"),URL_LOG("URL"),RESPONSE_LOG("RESPONSE"),EXCEPTION_LOG("COMVIVASDK EXCEPTION"),DEBUG_LOG("COMVIVASDK DEBUG"),DEBUG_METHOD("ENTERED INTO"),ERROR_LOG("COMVIVASDK ERROR"),
    PROVISIONING_STATUS("provisioningStatus"),
    REQUIRE_ADDITIONAL_AUTHENTICATION("REQUIRE_ADDITIONAL_AUTHENTICATION"),
    APPROVED("APPROVED"),
    STEPUP_REQUEST_ID("stepUpRequestID"),
    GUID("guid"),
    FAILURE_REASON("failureReason"),
    REASON("reason"),
    ASSET_ID("assetId"),
    REPERSO("reperso"),
    ENCRYPTION_META_DATA("encryptionMetaData"),
    VPAN_ENROLLMENT_ID("vPanEnrollmentID"),
    vpan_ENROLLMENT_ID("vpanEnrollmentID"),
    V_PROVISIONED_TOKEN_ID_SMALLP("vprovisionedTokenID"),
    RESPONSE_CODE("responseCode"),
    CARD_STATUS("cardStatus"),
    STATUS("status"),
    SUBTYPE("SUBTYPE"),
    MDES_LCM("MDES_LCM"),
    MDES_TXN("MDES_TXN"),
    CARD_IDENTIFIER("cardIdentifier"),
    VALUE("value"),
    VALUE_FOR_MINUTES("validForMinutes"),
    REASON_CODE("reasonCode"),
    MESSAGE("message"),
    OPERATION("operation"),
    PAN_SOURCE("panSource"),
    HVT_SUPPPORT("isHvtSupported"),
    HVT_LIMIT("hvtThreshold"),
    LOCALE("locale"),
    ENC_PAYMENT_INSTRUMENT("encPaymentInstrument"),


    //Asset Type and Content Type
    APPLICATION_PDF("application/pdf"),
    IMAGE_SLASH_PNG("image/png"),
    IMAGE_PNG("IMAGE"),
    IMAGE_PDF("image/pdf"),
    TEXT_PLAIN("text/plain"),
    TEXT_SLASH_HTML("text/html"),
    DIGITAL_CARD_ART("digitalCardArt"),
    DIGITAL_CARD_ART_BACKGROUND("digitalCardArtBackground"),
    CARD_SYMBOL_TAG("cardSymbol"),
    TERMS_AND_CONDITIONS_TAG("termsAndConditions"),
    TEXT_HTML("TEXT_HTML"),

    //DEVICE
    OS_TYPE("osType"),DEVICE_TYPE("deviceType"),DEVICE_NAME("deviceName"),OS_VERSION("osVersion"),OS_BUILD("osBuildID"),DEVICE_ID_TYPE("deviceIDType"),DEVICE_MANUFACTURER("deviceManufacturer"),DEVICE_BRAND("deviceBrand");

    private String tag;

    private Tags(String tag) {
        this.tag = tag;
    }

    public String getTag() {
        return tag;
    }
}